-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1:3306
-- Tiempo de generación: 01-05-2022 a las 11:41:28
-- Versión del servidor: 10.5.12-MariaDB-cll-lve
-- Versión de PHP: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `u254792697_mydaytoday`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `jsons`
--

CREATE TABLE `jsons` (
  `json` varchar(9999) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `idJSON` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla `jsons`
--

INSERT INTO `jsons` (`json`, `idJSON`) VALUES
('{\"infinitive\":\"Eat out\",\"root\":\"Eat\",\"addon\":\"out\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Have a meal in a restaurant or a café\",\"examples\":[\"I don´t want to cook, let´s eat out tonight.\"]}]}', 49),
('{\"infinitive\":\"Turn on\",\"root\":\"Turn\",\"addon\":\"on\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Start the function of a machine, equipment, etc.\",\"examples\":[\"I turned on the radio to listen to the lastest news.\"]}]}', 50),
('{\"infinitive\":\"Go down\",\"root\":\"Go\",\"addon\":\"Down\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Decrease\",\"examples\":[\"The prices go down after Christmas.\"]}]}', 51),
('{\"infinitive\":\"Slow down\",\"root\":\"Slow\",\"addon\":\"down\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Move more slowly.\",\"examples\":[\"The car slowed down as it approached the crossroad.\"]}]}', 52),
('{\"infinitive\":\"Turn down\",\"root\":\"Turn\",\"addon\":\"down\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Reduce (the volume).\",\"examples\":[\"Turn down the music, it´s too loud!\"]}]}', 53),
('{\"infinitive\":\"Put down\",\"root\":\"Put\",\"addon\":\"down\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Stop holding and put somewhere.\",\"examples\":[\"He stopped writing and put down his pen.\"]}]}', 54),
('{\"infinitive\":\"Take away\",\"root\":\"Take\",\"addon\":\"away\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Remove.\",\"examples\":[\"We asked the waiter to take our plates away.\"]}]}', 55),
('{\"infinitive\":\"Cut off\",\"root\":\"Cut\",\"addon\":\"off\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Stop supply; remove something by cutting.\",\"examples\":[\"Our telephone was cut off because we forgot to pay the bill.\"]}]}', 56),
('{\"infinitive\":\"Get off\",\"root\":\"Get\",\"addon\":\"off\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Leave the bus, train.\",\"examples\":[\"Let´s get off the bus and walk a little.\"]}]}', 57),
('{\"infinitive\":\"Put off\",\"root\":\"Put\",\"addon\":\"off\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Postpone, delay.\",\"examples\":[\"We have to put off the meeting until Friday.\"]}]}', 58),
('{\"infinitive\":\"See off\",\"root\":\"See\",\"addon\":\"off\",\"aux\":\"sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Go to say goodbye to someone who is leaving.\",\"examples\":[\"My friend came to the airport to see me off.\"]}]}', 59),
('{\"infinitive\":\"Turn off\",\"root\":\"Turn\",\"addon\":\"off\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Leave the ground and start flying.\",\"examples\":[\"Our plane took off on time.\"]}]}', 60),
('{\"infinitive\":\"Come back\",\"root\":\"Come\",\"addon\":\"back\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Return to a place.\",\"examples\":[\"I´ve just come back from my holiday in Bali.\"]}]}', 61),
('{\"infinitive\":\"Fall over\",\"root\":\"Fall\",\"addon\":\"Over\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Fall on the ground.\",\"examples\":[\"Suddenly, I lost my balance and fell over.\"]}]}', 62),
('{\"infinitive\":\"Hear of \",\"root\":\"Hear\",\"addon\":\"of\",\"aux\":\"sth/sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Know about something or somebody. To have news.\",\"examples\":[\"I´ve heard nothing of them since 2013.\"]}]}', 63),
('{\"infinitive\":\"Look through\",\"root\":\"Look\",\"addon\":\"through\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Read quickly.\",\"examples\":[\"I looked through my notes before the exam.\"]}]}', 64),
('{\"infinitive\":\"Name after\",\"root\":\"Name\",\"addon\":\"after\",\"aux\":\"sth/sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Give someone a name to remember another person.\",\"examples\":[\"He was named after his father.\"]}]}', 65),
('{\"infinitive\":\"Fool around\",\"root\":\"Fool\",\"addon\":\"around\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Have fun or behave in a silly way.\",\"examples\":[\"They spent all the day fooling around on the beach.\"]}]}', 66),
('{\"infinitive\":\"Run around\",\"root\":\"Run\",\"addon\":\"around\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Be very busy doing a lot of different things.\",\"examples\":[\"I ran around all day yesterday.\"]}]}', 67),
('{\"infinitive\":\"Break up\",\"root\":\"Break\",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"End a relationship.\",\"examples\":[\"Tom and Sally broke up after 5 years of marriage.\"]}]}', 68),
('{\"infinitive\":\"Do up\",\"root\":\"Do\",\"addon\":\"up\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Fasten.\",\"examples\":[\"Could you help me do up my dress?\"]}]}', 69),
('{\"infinitive\":\"Dress up\",\"root\":\"Dress\",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Wear smart or special clothes.\",\"examples\":[\"We don´t have a dress code and I don´t have to dress up for work.\"]}]}', 70),
('{\"infinitive\":\"Fill up\",\"root\":\"Fill\",\"addon\":\"up\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Fill to the top, make or become full.\",\"examples\":[\"Fill this bottle up with water, please.\"]}]}', 71),
('{\"infinitive\":\"Heat up\",\"root\":\"Heat\",\"addon\":\"up\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Make something warmer or hotter.\",\"examples\":[\"You can heat up the soup in the microwave.\"]}]}', 72),
('{\"infinitive\":\"Mix up\",\"root\":\"Mix\",\"addon\":\"up\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Confuse.\",\"examples\":[\"I always mix those twins up, they look so like each other.\"]}]}', 73),
('{\"infinitive\":\"Queue up\",\"root\":\"Queue\",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Wait in line with other people.\",\"examples\":[\"We queued up to get the tickets for the film.\"]}]}', 74),
('{\"infinitive\":\"Set up\",\"root\":\"Set\",\"addon\":\"up\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Start a company.\",\"examples\":[\"He set up his first business at the age of 27.\"]}]}', 75),
('{\"infinitive\":\"Stay up\",\"root\":\"Stay\",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Not going to bed.\",\"examples\":[\"Don´t stay up too late before the exam.\"]}]}', 76),
('{\"infinitive\":\"Break into\",\"root\":\"Break\",\"addon\":\"into\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Enter a building or an apartment by force to steal something.\",\"examples\":[\"The thieves broke into the house when the Johnsons were away on holiday.\"]}]}', 77),
('{\"infinitive\":\"Hand in\",\"root\":\"Hand\",\"addon\":\"in\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Submit. Give something to someone in authority.\",\"examples\":[\"We must hand in our essays on Friday.\"]}]}', 78),
('{\"infinitive\":\"Let in\",\"root\":\"Let\",\"addon\":\"in\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Allow someone to enter.\",\"examples\":[\"I knocked on the door and they let me in.\"]}]}', 79),
('{\"infinitive\":\"Go in\",\"root\":\"Go\",\"addon\":\"in\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Like, enjoy something.\",\"examples\":[\"Do you go in for sport?\"]}]}', 80),
('{\"infinitive\":\"Carry on\",\"root\":\"Carry\",\"addon\":\"on\",\"aux\":\"with\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Continue doing something.\",\"examples\":[\"Carry on with your work till the end of the lesson.\"]}]}', 81),
('{\"infinitive\":\"Get on\",\"root\":\"Get\",\"addon\":\"on\",\"aux\":\"with\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Have a friendly relationship.\",\"examples\":[\"Do you get on well with your colleagues?\"]}]}', 82),
('{\"infinitive\":\"Live on\",\"root\":\"Live\",\"addon\":\"on\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Have a particular amount of money to buy the things you need.\",\"examples\":[\"The pension is too small to live on.\"]}]}', 83),
('{\"infinitive\":\"Rely on\",\"root\":\"Rely\",\"addon\":\"on\",\"aux\":\"sth/sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Trust.\",\"examples\":[\"If you need some help you can always rely on me.\"]}]}', 84),
('{\"infinitive\":\"Insist on\",\"root\":\"Insist\",\"addon\":\"on\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Demand.\",\"examples\":[\"His parents wanted him to be a lawyer, but he insisted on a career as a musician.\"]}]}', 85),
('{\"infinitive\":\"Cross out\",\"root\":\"Cross\",\"addon\":\"out\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Draw a line through something.\",\"examples\":[\"If you make a mistake just cross it out.\"]}]}', 86),
('{\"infinitive\":\"Hand out\",\"root\":\"Hand\",\"addon\":\"out\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Distribute to a group of people.\",\"examples\":[\"The teacher handed out the test papers to the class.\"]}]}', 87),
('{\"infinitive\":\"Let out\",\"root\":\"Let\",\"addon\":\"out\",\"aux\":\"sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Allow somebody to leave or go out.\",\"examples\":[\"I don´t like that my neighbours let out their dogs at night.\"]}]}', 88),
('{\"infinitive\":\"Look out\",\"root\":\"Look\",\"addon\":\"out\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Be careful.\",\"examples\":[\"Look out! There is a car coming!\"]}]}', 89),
('{\"infinitive\":\"Rent out\",\"root\":\"Rent\",\"addon\":\"out\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Allow somebody to use something in return for payment.\",\"examples\":[\"Most apartments in this building are rented out to students.\"]}]}', 90),
('{\"infinitive\":\"Take out\",\"root\":\"Take\",\"addon\":\"out\",\"aux\":\"sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Invite somebody to go with you somewhere.\",\"examples\":[\"They took the children out to the zoo.\"]}]}', 91),
('{\"infinitive\":\"Work out\",\"root\":\"Work\",\"addon\":\"out\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Exercise.\",\"examples\":[\"I work out in the gym twice a week.\"]}]}', 92),
('{\"infinitive\":\"Note down\",\"root\":\"Note\",\"addon\":\"down\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Write something, so that you don´t forget it.\",\"examples\":[\"Did you note down this phone number?\"]}]}', 93),
('{\"infinitive\":\"Shut down\",\"root\":\"Shut\",\"addon\":\"down\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Stop operating. Close a business.\",\"examples\":[\"The café shut down after numerous complaints from customers.\"]}]}', 94),
('{\"infinitive\":\"Give away\",\"root\":\"Give\",\"addon\":\"away\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Give something for free.\",\"examples\":[\"They are giving away free tickets for the concert.\"]}]}', 95),
('{\"infinitive\":\"Keep away\",\"root\":\"Keep\",\"addon\":\"away\",\"aux\":\"from\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Not allow someone to go or be near something.\",\"examples\":[\"You should keep away from this dangerous area.\"]}]}', 96),
('{\"infinitive\":\"Pass by\",\"root\":\"Pass\",\"addon\":\"by\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Go past without stopping.\",\"examples\":[\"He was just passing by when he saw the accident.\"]}]}', 97),
('{\"infinitive\":\"Put aside\",\"root\":\"Put\",\"addon\":\"aside\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Save money for a particular purpose.\",\"examples\":[\"I put aside 100 euros a month for my summer holidays.\"]}]}', 98),
('{\"infinitive\":\"Get back\",\"root\":\"Get\",\"addon\":\"back\",\"aux\":\"from\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Return to a place, activity.\",\"examples\":[\"What time will you get back from work?\"]}]}', 99),
('{\"infinitive\":\"Take back\",\"root\":\"Take\",\"addon\":\"back\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Return something. Return words.\",\"examples\":[\"I need to take the books back to the library next week.\"]}]}', 100),
('{\"infinitive\":\"Put back sth\",\"root\":\"Put\",\"addon\":\"back\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Put something where it was before.\",\"examples\":[\"Can you put these books back on the shelves, please?\"]}]}', 101),
('{\"infinitive\":\"Pay off\",\"root\":\"Pay\",\"addon\":\"off\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Pay all of your debt.\",\"examples\":[\"He is working hard to pay off his debts.\"]}]}', 102),
('{\"infinitive\":\"Set off\",\"root\":\"Set\",\"addon\":\"off\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Start a journey.\",\"examples\":[\"When do you set off for Asia?\"]}]}', 103),
('{\"infinitive\":\"Consist of sth\",\"root\":\"Consist\",\"addon\":\"of\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Be made up of two or more parts or things.\",\"examples\":[\"Breakfast consisted of eggs, ham, bread and coffee.\"]}]}', 104),
('{\"infinitive\":\"Deal with sth/sb\",\"root\":\"Deal\",\"addon\":\"with\",\"aux\":\"sth/sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Handle, take care of.\",\"examples\":[\"Unfortunately, we were not prepared to deal with that sort of situations.\"]}]}', 105),
('{\"infinitive\":\"Get together\",\"root\":\"Get\",\"addon\":\"together\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Meet, spend time together.\",\"examples\":[\"Our team got together to discuss a problem.\"]}]}', 106),
('{\"infinitive\":\"Leave behind sth/sb\",\"root\":\"Leave\",\"addon\":\"behind\",\"aux\":\"sth/sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Not take something or somebody with you.\",\"examples\":[\"I was in a hurry and left my keys behind.\"]}]}', 107),
('{\"infinitive\":\"Take after\",\"root\":\"Take\",\"addon\":\"after\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Look like. Resemble someone in your family.\",\"examples\":[\"She takes after her mother, both in appearance and character.\"]}]}', 108),
('{\"infinitive\":\"Lead to sth\",\"root\":\"Lead\",\"addon\":\"to\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Result in.\",\"examples\":[\"Everybody knows that stress can lead to illness.\"]}]}', 109),
('{\"infinitive\":\"Add up sth\",\"root\":\"Add\",\"addon\":\"up\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Calculate.\",\"examples\":[\"He is a smart boy and can easily add up numbers in his head.\"]}]}', 110),
('{\"infinitive\":\"Catch up with\",\"root\":\"Catch\",\"addon\":\"up\",\"aux\":\"with\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Stop being behind, reach the same standard or rate.\",\"examples\":[\"I´ve missed many lessons so it will be hard to catch up.\"]}]}', 111),
('{\"infinitive\":\"Clear up sth\",\"root\":\"Clear\",\"addon\":\"up\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Make a place clean and tidy.\",\"examples\":[\"Can you help me clear up the table after dinner?\"]}]}', 112),
('{\"infinitive\":\"Keep up with\",\"root\":\"Keep\",\"addon\":\"up\",\"aux\":\"with\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Continue at the same rate, level.\",\"examples\":[\"He walks too fast and it´s hard for me to keep up with him.\"]}]}', 113),
('{\"infinitive\":\"Mess up sth\",\"root\":\"Mess\",\"addon\":\"up\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Spoil or damage.\",\"examples\":[\"I made a mistake that messed up my work.\"]}]}', 114),
('{\"infinitive\":\"Put up with\",\"root\":\"Put\",\"addon\":\"up\",\"aux\":\"with\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Tolerate, accept something unpleasant.\",\"examples\":[\"I will never put up with smoking in the office.\"]}]}', 115),
('{\"infinitive\":\"Set up sth\",\"root\":\"Set \",\"addon\":\"up\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Organize, plan (a meeting).\",\"examples\":[\"Let´s set up a meeting for Monday.\"]}]}', 116),
('{\"infinitive\":\"Crack up\",\"root\":\"Crack\",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To laugh uncontrollably.\",\"examples\":[\"It was so funny I cracked up.\"]},{\"spanish\":\"\",\"english\":\"To undergo a physical or mental breakdown.\",\"examples\":[\"I haven´t slept for days, I´m close to cracking up.\"]}]}', 117),
('{\"infinitive\":\"Show up\",\"root\":\"Show\",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Arrive, appear, attend something.\",\"examples\":[\"We waited for him all the evening but he didn´t show up.\"]}]}', 118),
('{\"infinitive\":\"Split up\",\"root\":\"Split \",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Finish a relationship.\",\"examples\":[\"They split up after 10 years of marriage.\"]}]}', 119),
('{\"infinitive\":\"Sum up sth\",\"root\":\"Sum\",\"addon\":\"up\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Give a summary. Describe briefly.\",\"examples\":[\"At the end of the lesson, the teacher summed up the main points.\"]}]}', 120),
('{\"infinitive\":\"Take up sth\",\"root\":\"Take \",\"addon\":\"up\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Start a new hobby.\",\"examples\":[\"She took up yoga last year.\"]}]}', 121),
('{\"infinitive\":\"Carry out sth\",\"root\":\"Carry\",\"addon\":\"out\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Do or complete sth. Perform a task.\",\"examples\":[\"The government carried out the reforms that had promised.\"]}]}', 122),
('{\"infinitive\":\"Come out\",\"root\":\"Come\",\"addon\":\"out\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Exit. Be published. Become available.\",\"examples\":[\"Please come out, we need to go now.\"]}]}', 123),
('{\"infinitive\":\"Fall out with\",\"root\":\"Fall\",\"addon\":\"out\",\"aux\":\"with\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Have an argument with somebody.\",\"examples\":[\"Anne felt depressed because she had fallen out with her husband.\"]}]}', 124),
('{\"infinitive\":\"Point out sth\",\"root\":\"Point\",\"addon\":\"out\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Indicate. Show.\",\"examples\":[\"The teacher pointed out some spelling mistakes in my dictation.\"]}]}', 125),
('{\"infinitive\":\"Put out sth\",\"root\":\"Put \",\"addon\":\"out\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Extinguish. Stop something burning.\",\"examples\":[\"The fire brigade put out the fire quickly.\"]}]}', 126),
('{\"infinitive\":\"Turn out\",\"root\":\"Turn\",\"addon\":\"out\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Happen in a particular way or have a result.\",\"examples\":[\"The exam turned out to be easier than we expected.\"]}]}', 127),
('{\"infinitive\":\"Work out\",\"root\":\"Work\",\"addon\":\"out\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Find a solution. Understand.\",\"examples\":[\"I hope we can work out all our problems.\"]}]}', 128),
('{\"infinitive\":\"Leave out sth/sb\",\"root\":\"Leave\",\"addon\":\"out\",\"aux\":\"sth/sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Not include. Omit.\",\"examples\":[\"I decided to leave out the details of the story.\"]}]}', 129),
('{\"infinitive\":\"Sort out sth\",\"root\":\"Sort\",\"addon\":\"out\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Deal with a problem successfully.\",\"examples\":[\"Tell me about your problems and we will try to sort them out.\"]}]}', 130),
('{\"infinitive\":\"Cut down on\",\"root\":\"Cut\",\"addon\":\"down\",\"aux\":\"on\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Reduce the amount.\",\"examples\":[\"She is trying to cut down on the amount of sugar she eats every day.\"]}]}', 131),
('{\"infinitive\":\"Keep down sth\",\"root\":\"Keep\",\"addon\":\"down\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Stop from increasing.\",\"examples\":[\"The government is trying to keep inflaction down.\"]}]}', 132),
('{\"infinitive\":\"Let down sb\",\"root\":\"Let \",\"addon\":\"down\",\"aux\":\"sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Disappoint.\",\"examples\":[\"Please, keep your promise. Don´t let me down.\"]}]}', 133),
('{\"infinitive\":\"Settle down\",\"root\":\"Settle\",\"addon\":\"down\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Start living a quieter life in one place.\",\"examples\":[\"Now, he wants to settle down and have a family.\"]}]}', 134),
('{\"infinitive\":\"Call off sth\",\"root\":\"Call\",\"addon\":\"off\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Cancel.\",\"examples\":[\"The competition was called off because of the bad weather.\"]}]}', 135),
('{\"infinitive\":\"Live off sth/sb\",\"root\":\"Live\",\"addon\":\"off\",\"aux\":\"sth/sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Depend on something or someone for money.\",\"examples\":[\"He is unemployed at the moment and he is living off his parents.\"]}]}', 136),
('{\"infinitive\":\"Rip off sb\",\"root\":\"Rip\",\"addon\":\"off\",\"aux\":\"sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Cheat. Charge too much money for something.\",\"examples\":[\"Taxi drivers sometimes rip off foreign tourists.\"]}]}', 137),
('{\"infinitive\":\"Start up sth\",\"root\":\"Start\",\"addon\":\"up\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Begin a new business, organisation, etc.\",\"examples\":[\"We started up some important projects last year.\"]}]}', 138),
('{\"infinitive\":\"Tell off sb\",\"root\":\"Tell\",\"addon\":\"off\",\"aux\":\"sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Speak angrily to someone. Criticise.\",\"examples\":[\"The teacher told him off for not doing his homework.\"]}]}', 139),
('{\"infinitive\":\"Devote sth to sb\",\"root\":\"Devote to\",\"addon\":\"\",\"aux\":\"sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Dedicate. Spend a lot of time and effort.\",\"examples\":[\"She left her job and devoted all her time to her family.\"]}]}', 140),
('{\"infinitive\":\"Object to sth/sb\",\"root\":\"Object\",\"addon\":\"to\",\"aux\":\"sth/sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Disagree with. Disapprove of.\",\"examples\":[\"Most of the employees strongly object to the new rules.\"]}]}', 141),
('{\"infinitive\":\"Occur to sb\",\"root\":\"Occur\",\"addon\":\"to\",\"aux\":\"sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Come to one´s mind.\",\"examples\":[\"It never occurred to me that he might be lying to me.\"]}]}', 142),
('{\"infinitive\":\"Refer to sth/sb\",\"root\":\"Refer\",\"addon\":\"to\",\"aux\":\"sth/sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Mention or talk about something or somebody.\",\"examples\":[\"In her book, she often refers to her happy childhood.\"]}]}', 143),
('{\"infinitive\":\"Relate to\",\"root\":\"Relate\",\"addon\":\"to\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Be about something or be connected with something.\",\"examples\":[\"This article relates to the economic situation in the country.\"]}]}', 144),
('{\"infinitive\":\"Stick to\",\"root\":\"Stick \",\"addon\":\"to\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Continue and not change.\",\"examples\":[\"We need to stick to our original plan.\"]}]}', 145),
('{\"infinitive\":\"Get away with\",\"root\":\"Get\",\"addon\":\"away\",\"aux\":\"with\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Do something bad without being punished.\",\"examples\":[\"He got away with cheating in his test again.\"]}]}', 146),
('{\"infinitive\":\"Pass away\",\"root\":\"Pass\",\"addon\":\"away\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Die.\",\"examples\":[\"His grandfather passed away at the age of 98.\"]}]}', 147),
('{\"infinitive\":\"Dive into sth\",\"root\":\"Dive\",\"addon\":\"into\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Start something suddenly and energetically.\",\"examples\":[\"Don´t dive into this work without preparation.\"]}]}', 148),
('{\"infinitive\":\"Stand for sth\",\"root\":\"Stand\",\"addon\":\"for\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Mean. Represent.\",\"examples\":[\"UNO stands for United Nations Organisation.\"]}]}', 149),
('{\"infinitive\":\"Turn into sth\",\"root\":\"Turn\",\"addon\":\"into\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Change or become something different.\",\"examples\":[\"I hope this problem doesn´t turn into a crisis.\"]}]}', 150),
('{\"infinitive\":\"Get along with\",\"root\":\"Get\",\"addon\":\"along\",\"aux\":\"with\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Have a friendly relationship.\",\"examples\":[\"She doesn´t get along with her sister.\"]}]}', 151),
('{\"infinitive\":\"Get over sth\",\"root\":\"Get\",\"addon\":\"over\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Recover. Feel better.\",\"examples\":[\"It can take long time to get over a disease like that.\"]}]}', 152),
('{\"infinitive\":\"Hang around sth\",\"root\":\"Hang\",\"addon\":\"around\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Spend time not doing much.\",\"examples\":[\"Those guys usually hang around the beach all day.\"]}]}', 153),
('{\"infinitive\":\"Ask out\",\"root\":\"Ask\",\"addon\":\"out\",\"aux\":\"sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To invite someone to a social engagement.\",\"examples\":[\"Ellen asked me out and I said yes.\"]}]}', 154),
('{\"infinitive\":\"Be off\",\"root\":\"Be\",\"addon\":\"off\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Leave a place or depart to another one.\",\"examples\":[\"I think I will be off. See you later!\"]}]}', 155),
('{\"infinitive\":\"Blow up\",\"root\":\"Blow\",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To explode something.\",\"examples\":[\"Our pressure cooker blew up yesterday.\"]}]}', 156),
('{\"infinitive\":\"Blow out\",\"root\":\"Blow\",\"addon\":\"out\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To extinguish something (typically a flame) with some form of air, such as breath or wind.\",\"examples\":[\"Make a wish before you blow out the candles.\"]}]}', 157),
('{\"infinitive\":\"Bring up\",\"root\":\"Bring\",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To raise someone or something. To care for someone or something up to adulthood. \",\"examples\":[\"I was brought up in Spain.\"]},{\"spanish\":\"\",\"english\":\"To mention someone or something.\",\"examples\":[\"Sorry to bring this up again, but we should organise our meeting.\"]}]}', 158),
('{\"infinitive\":\"Butt in\",\"root\":\"Butt\",\"addon\":\"in\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"Please, stop butting in! I need to talk.\",\"english\":\"To interrupt someone or something.\",\"examples\":[\"\"]}]}', 159),
('{\"infinitive\":\"Care about sth/sb\",\"root\":\"Care\",\"addon\":\"about\",\"aux\":\"sth/sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To have a strong feeling of love or affection for something or someone.\",\"examples\":[\"There is nothing I care about more than my children.\"]}]}', 160),
('{\"infinitive\":\"Chop up\",\"root\":\"Chop\",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To cut or slice something into smaller pieces. \",\"examples\":[\"You can chop up the tomato, while I boil the pasta.\"]}]}', 161),
('{\"infinitive\":\"Close down\",\"root\":\"Close \",\"addon\":\"down\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To cease business operations for any length of time (often permanently).\",\"examples\":[\"That Chinese restaurant had to close down after the inspection.\"]}]}', 162),
('{\"infinitive\":\"Come across\",\"root\":\"Come\",\"addon\":\"across\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To find or see something or someone incidentally.\",\"examples\":[\"I came across a 50 euros bill on my way to work this afternoon!\"]}]}', 163),
('{\"infinitive\":\"Come down with\",\"root\":\"Come \",\"addon\":\"down\",\"aux\":\"with\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To become ill.\",\"examples\":[\"I really think I am coming down with something.\"]}]}', 164),
('{\"infinitive\":\"Doze off\",\"root\":\"Doze\",\"addon\":\"off\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To fall asleep, typically unexpectedly or for just a short period of time.\",\"examples\":[\"Suzanne dozzed off on the sofa.\"]}]}', 165),
('{\"infinitive\":\"Drop in\",\"root\":\"Drop \",\"addon\":\"in\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To let go of something so that it enters something else.\",\"examples\":[\"He just dropped his donation into the yellow envelope.\"]},{\"spanish\":\"\",\"english\":\"To come to some place for a casual visit.\",\"examples\":[\"I´m working right now. Can you drop in later?\"]}]}', 166),
('{\"infinitive\":\"Eat up\",\"root\":\"Eat\",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To eat something, especially to eat all of it.\",\"examples\":[\"Come on, eat it up. It will make you stronger.\"]}]}', 167),
('{\"infinitive\":\"End up sth\",\"root\":\"End\",\"addon\":\"up\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To conclude something.\",\"examples\":[\"He ended up saying that he was wrong!\"]}]}', 168),
('{\"infinitive\":\"Fall behind\",\"root\":\"Fall\",\"addon\":\"behind\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To not be as current with task or activity as one should or ideally would be.\",\"examples\":[\"They have fallen behind on their mortgage payments and now they are extremely worried.\"]}]}', 169),
('{\"infinitive\":\"Fill in for sb\",\"root\":\"Fill\",\"addon\":\"in\",\"aux\":\"for sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To substitute for someone or something.\",\"examples\":[\"Could you fill in for me next week? I am not feeling well.\"]},{\"spanish\":\"\",\"english\":\"To inform one of something.\",\"examples\":[\"Fill me in—what happened at the party two days ago?\"]}]}', 170),
('{\"infinitive\":\"Get away from\",\"root\":\"Get\",\"addon\":\"away\",\"aux\":\"from\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To move away from someone or something.\",\"examples\":[\"Be careful! Get away from that street!\"]}]}', 171),
('{\"infinitive\":\"Get down sb\",\"root\":\"Get \",\"addon\":\"down\",\"aux\":\"sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To cause one to feel saddened, depressed, discouraged, or dejected.\",\"examples\":[\"Don´t let these comments get you down, darling!\"]}]}', 172),
('{\"infinitive\":\"Give in\",\"root\":\"Give\",\"addon\":\"in\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\" To collapse, crumble, or cave in.\",\"examples\":[\"They were able to get the kids out of the house before that roof gave in.\"]},{\"spanish\":\"\",\"english\":\"To hand in, deliver, or submit (something).\",\"examples\":[\"Please give in your papers before tomorrow.\"]},{\"spanish\":\"\",\"english\":\"To cease opposition; yield.\",\"examples\":[\"The headmaster finally gave in to our demands.\"]}]}', 173),
('{\"infinitive\":\"Go away\",\"root\":\"Go\",\"addon\":\"away\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To leave a place\",\"examples\":[\"Go away right now. I want to be alone!\"]},{\"spanish\":\"\",\"english\":\"To take a vacation or short trip.\",\"examples\":[\"The family went away for a few days.\"]},{\"spanish\":\"\",\"english\":\"To stop existing or disappear\",\"examples\":[\"It took a long time for the pain to go away.\"]}]}', 174),
('{\"infinitive\":\"Go off\",\"root\":\"Go\",\"addon\":\"off\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"T leave a place and go somewhere else.\",\"examples\":[\"He went off as soon as he could.\"]},{\"spanish\":\"\",\"english\":\"If a light or machine goes off, it stops working.\",\"examples\":[\"The heating goes off at ten o’clock.\"]},{\"spanish\":\"\",\"english\":\"If something that makes a noise goes off, it suddenly starts making a noise.\",\"examples\":[\"My alarm didn´t go off this morning.\"]},{\"spanish\":\"\",\"english\":\"If food goes off, it stops being good to eat because it is too old.\",\"examples\":[\"Keep the meat in the fridge or it will go off.\"]},{\"spanish\":\"\",\"english\":\"To stop liking.\",\"examples\":[\"I´ve gone off Martin since he told me about his personal projects.\"]}]}', 175),
('{\"infinitive\":\"Go through\",\"root\":\"Go\",\"addon\":\"through\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To have an unpleasant experience.\",\"examples\":[\"I have been through a lot these last months.\"]},{\"spanish\":\"\",\"english\":\"To look at thoroughly.\",\"examples\":[\"I went through every room in the apartment to find it.\"]},{\"spanish\":\"\",\"english\":\"To think about carefully.\",\"examples\":[\"In this lesson, we will go throw the past tenses.\"]}]}', 176),
('{\"infinitive\":\"Hang on\",\"root\":\"Hang\",\"addon\":\"on\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To wait for a short time.\",\"examples\":[\"Hang on a moment, I need to take my umbrella.\"]},{\"spanish\":\"\",\"english\":\"To hold on to sth with a strong grip.\",\"examples\":[\"Hang on tight!\"]},{\"spanish\":\"\",\"english\":\"To persist tenaciously.\",\"examples\":[\"That cold hung on all spring, how horrible it was!\"]}]}', 177),
('{\"infinitive\":\"Hang up sth\",\"root\":\"Hang\",\"addon\":\"up\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To place on a hook or hanger designed for the purpose.\",\"examples\":[\"Hang up your towel, it is totally wet!\"]},{\"spanish\":\"\",\"english\":\"To break a telephone connection\",\"examples\":[\"Please, don´t hang up. I want to talk a little bit more.\"]}]}', 178),
('{\"infinitive\":\"Head back\",\"root\":\"Head \",\"addon\":\"back\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To begin the act of returning to some place or thing.\",\"examples\":[\"It is getting dark, we could head back home now.\"]}]}', 179),
('{\"infinitive\":\"Hold on\",\"root\":\"Hold\",\"addon\":\"on\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To wait.\",\"examples\":[\"Hold on, we are almost there.\"]},{\"spanish\":\"\",\"english\":\"To keep a firm grip on.\",\"examples\":[\"Hold on tight to the railing.\"]},{\"spanish\":\"\",\"english\":\"To keep sth you already have.\",\"examples\":[\"Hold on your ticket, it will be necessary for the cinema.\"]}]}', 180),
('{\"infinitive\":\"Keep on\",\"root\":\"Keep\",\"addon\":\"on\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To continue happening, doing something, working, etc.\",\"examples\":[\"Don´t keep on calling me, please.\"]},{\"spanish\":\"\",\"english\":\"To continue to have (someone) as an employee.\",\"examples\":[\"The company kept me on to teach people.\"]}]}', 181),
('{\"infinitive\":\"Keep up\",\"root\":\"Keep\",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To keep adequately informed or up-to-date.\",\"examples\":[\"Keep me up on international affairs.\"]},{\"spanish\":\"\",\"english\":\"To stay with someone who is moving forward by moving as quickly as them.\",\"examples\":[\"He walked so fast that I could not easily keep him up.\"]}]}', 182),
('{\"infinitive\":\"Keep it up\",\"root\":\"Keep \",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To carry on doing something at the same speed or as well as one is doing it at present.\",\"examples\":[\"Very good, keep it up Elle!\"]}]}', 183),
('{\"infinitive\":\"Kick out\",\"root\":\"Kick\",\"addon\":\"out\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To force to leave.\",\"examples\":[\"The English teacher kicked us out for throwing pencils.\"]}]}', 184),
('{\"infinitive\":\"Knock out\",\"root\":\"Know\",\"addon\":\"out\",\"aux\":\"sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To cause to become unconscious.\",\"examples\":[\"Drugs sometimes knock people out.\",\"The boxer knocked this opponent out.\"]},{\"spanish\":\"\",\"english\":\"To surprise someone.\",\"examples\":[\"Her incredible voice knocked everyone out.\"]}]}', 185),
('{\"infinitive\":\"Knock over\",\"root\":\"Knock\",\"addon\":\"over\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To cause to fall from an upright position.\",\"examples\":[\"The kid knocked over the plate.\"]}]}', 186),
('{\"infinitive\":\"Knock down\",\"root\":\"Knock\",\"addon\":\"down\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To hit somebody with a vehicle, causing them to fall.\",\"examples\":[\"She was knocked down by a bus.\"]},{\"spanish\":\"\",\"english\":\"To demolish a building.\",\"examples\":[\"They’re knocking down the houses to make way for a new shopping centre.\"]}]}', 187),
('{\"infinitive\":\"Let off sb\",\"root\":\"Let\",\"addon\":\"off\",\"aux\":\"sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To not punish sb at all or not as severely as you could have.\",\"examples\":[\"The teacher let him off with a warning.\"]}]}', 188),
('{\"infinitive\":\"Lighten up\",\"root\":\"Lighten\",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To become happier and less serious.\",\"examples\":[\"I wish she had lighten up.\"]}]}', 189),
('{\"infinitive\":\"Look into\",\"root\":\"\",\"addon\":\"\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To try to find more information about.\",\"examples\":[\"We are looking into ways to improve our service.\"]}]}', 190),
('{\"infinitive\":\"Make up\",\"root\":\"Make\",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To invent something.\",\"examples\":[\"She made up some story about getting lost.\"]},{\"spanish\":\"\",\"english\":\"To equal a particular number or part.\",\"examples\":[\"Hispanics make up more than 50% of the population.\"]},{\"spanish\":\"\",\"english\":\"To replace something or compensate for something.\",\"examples\":[\"You have to make up the work you missed.\"]},{\"spanish\":\"\",\"english\":\"To become friends again after an argument.\",\"examples\":[\"We had an argument but we finally made up.\"]}]}', 191),
('{\"infinitive\":\"Pick up\",\"root\":\"Pick\",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To use your hands to lift.\",\"examples\":[\"She picked up the baby.\"]},{\"spanish\":\"\",\"english\":\"To go to a place to get.\",\"examples\":[\"I have to go and pick up the kids from school.\"]},{\"spanish\":\"\",\"english\":\"To learn.\",\"examples\":[\"I picked up new phrasal verbs when I visited England.\",\"You’ve picked up some bad habits.\"]},{\"spanish\":\"\",\"english\":\"To become infected with an illness.\",\"examples\":[\"He picked up a cold in Germany.\"]},{\"spanish\":\"\",\"english\":\"To buy, get, or obtain easily or cheaply.\",\"examples\":[\"I picked up those t-shirts for 7 euros.\"]},{\"spanish\":\"\",\"english\":\"To start again in the place where you stopped.\",\"examples\":[\"We’ll pick up the discussion here tomorrow.\"]},{\"spanish\":\"\",\"english\":\"To answer a phone call.\",\"examples\":[\"I called four times but no one picked up.\"]}]}', 192),
('{\"infinitive\":\"Plug in\",\"root\":\"Plug\",\"addon\":\"in\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To connect up (an electrical apparatus) by inserting its plug into a socket.\",\"examples\":[\"You didn´t plug the toaster in.\"]}]}', 193),
('{\"infinitive\":\"Put on sth\",\"root\":\"Put\",\"addon\":\"on\",\"aux\":\"sth\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To pull a piece of clothing onto your body or attach jewelry to it.\",\"examples\":[\"He put on his Nike sneakers.\",\"Put the  earrings on.\"]}]}', 194),
('{\"infinitive\":\"Put on weight\",\"root\":\"Put\",\"addon\":\"on\",\"aux\":\"weight\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To become heavier.\",\"examples\":[\"She has put on a lot of weight during these months.\"]}]}', 195),
('{\"infinitive\":\"Put on weight\",\"root\":\"Put\",\"addon\":\"on\",\"aux\":\"weight\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To become heavier.\",\"examples\":[\"She has put on a lot of weight during these months.\"]}]}', 196),
('{\"infinitive\":\"Putting sb on\",\"root\":\"Putting\",\"addon\":\"on\",\"aux\":\"sb\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To pretend something is true as a trick.\",\"examples\":[\"She’s not 28 – you’re putting me on!\"]}]}', 197),
('{\"infinitive\":\"Put out\",\"root\":\"Put\",\"addon\":\"out\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To stop from burning.\",\"examples\":[\"It took firefighters many hours to put the fire out.\"]},{\"spanish\":\"\",\"english\":\"To move sth to a place that is easy to see or find.\",\"examples\":[\"Put the glass of milk out on the table.\"]},{\"spanish\":\"\",\"english\":\"To disturb, bother.\",\"examples\":[\"I need someone to check my mistakes, but I don´t want to put you out.\"]}]}', 198),
('{\"infinitive\":\"Put off\",\"root\":\"Put\",\"addon\":\"off\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To decide to do sth at a later time or date.\",\"examples\":[\"We have to put off the meeting until Sunday.\"]},{\"spanish\":\"\",\"english\":\"Discourage.\",\"examples\":[\"I´m sure that sushi is lovely, but the look of it really puts me off.\",\"These reviews have put me off going to that restaurant.\"]}]}', 199),
('{\"infinitive\":\"Rip off\",\"root\":\"Rip\",\"addon\":\"off\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To cheat somebody by taking money from them.\",\"examples\":[\"I got ripped off as soon as I left the shop.\"]},{\"spanish\":\"\",\"english\":\"To imitate a product, especially one of lower quality.\",\"examples\":[\"That artist ripped off my work.\"]},{\"spanish\":\"\",\"english\":\"To cut, tear apart, or tear away roughly or energetically.\",\"examples\":[\"The stripper has ripped off her shirt.\"]}]}', 200),
('{\"infinitive\":\"Run into\",\"root\":\"Run\",\"addon\":\"into\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To meet by chance.\",\"examples\":[\"I ran into my uncle in the supermarket.\"]},{\"spanish\":\"\",\"english\":\"To start having difficulties/trouble/problems etc.\",\"examples\":[\"Her business had run into tremendous difficulties.\"]}]}', 202),
('{\"infinitive\":\"Run over\",\"root\":\"Run\",\"addon\":\"over\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To hit with a vehicle.\",\"examples\":[\"Yesterday, my brother accidentally ran over a rabbit.\"]}]}', 203),
('{\"infinitive\":\"Show off\",\"root\":\"Show \",\"addon\":\"off\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To make other people admire your abilities or achievements in a way that is annoying.\",\"examples\":[\"Stop showing off your new Iphone. I cannot afford it!\"]},{\"spanish\":\"\",\"english\":\"To display something you are proud of.\",\"examples\":[\"This is an opportunity for teenagers to show off their abilities.\"]}]}', 204),
('{\"infinitive\":\"Sort out\",\"root\":\"Sort\",\"addon\":\"out\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"Deal with a problem successfully.\",\"examples\":[\"Tell me about your worries and we will try to sort them out.\"]},{\"spanish\":\"\",\"english\":\"To place or arrange according to class, kind, or size. To classify.\",\"examples\":[\"Sorted the CDs out into boxes by artists.\"]}]}', 205),
('{\"infinitive\":\"Turn down\",\"root\":\"Turn \",\"addon\":\"down\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To not accept an offer.\",\"examples\":[\"I turned down the job because of the salary.\"]},{\"spanish\":\"\",\"english\":\"To decrease the level of sound, heat, etc. that a device is producing.\",\"examples\":[\"Can you turn the tv down, please?\"]}]}', 206),
('{\"infinitive\":\"Work out\",\"root\":\"Work\",\"addon\":\"out\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To do exercises to make your body stronger.\",\"examples\":[\"I usually work out at 10 am.\"]},{\"spanish\":\"\",\"english\":\"If a problem or situation works out, it gradually becomes better.\",\"examples\":[\"I hope we can work it out as soon as possible.\"]},{\"spanish\":\"\",\"english\":\"Calculate.\",\"examples\":[\"How much does the company owe you? Let me work it out in a minute..\"]}]}', 207),
('{\"infinitive\":\"Zip up\",\"root\":\"Zip\",\"addon\":\"up\",\"aux\":\"\",\"meanings\":[{\"spanish\":\"\",\"english\":\"To fasten something with a zip.\",\"examples\":[\"She zipped up her coat.\"]}]}', 208);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `jsons`
--
ALTER TABLE `jsons`
  ADD PRIMARY KEY (`idJSON`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `jsons`
--
ALTER TABLE `jsons`
  MODIFY `idJSON` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=209;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
